//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWin_RichPresence.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMWin_RichPresence.Properties.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen on Apple Music.
        /// </summary>
        public static string DiscordButton_ListenOnAppleMusic {
            get {
                return ResourceManager.GetString("DiscordButton_ListenOnAppleMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Artist.
        /// </summary>
        public static string DiscordButton_ViewArtist {
            get {
                return ResourceManager.GetString("DiscordButton_ViewArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update for AMWin-RP is available. Would you like to view the releases?.
        /// </summary>
        public static string Message_AppUpdate {
            get {
                return ResourceManager.GetString("Message_AppUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available.
        /// </summary>
        public static string Message_AppUpdate_Title {
            get {
                return ResourceManager.GetString("Message_AppUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All saved lyrics have been deleted..
        /// </summary>
        public static string Message_ClearedLyricCache {
            get {
                return ResourceManager.GetString("Message_ClearedLyricCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Deleted.
        /// </summary>
        public static string Message_ClearedLyricCache_Title {
            get {
                return ResourceManager.GetString("Message_ClearedLyricCache_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all saved lyrics?.
        /// </summary>
        public static string Message_ClearLyricCache {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete lyrics: .
        /// </summary>
        public static string Message_ClearLyricCache_Fail {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved lyrics found..
        /// </summary>
        public static string Message_ClearLyricCache_FailNotFound {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache_FailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cached Lyrics.
        /// </summary>
        public static string Message_ClearLyricCache_Title {
            get {
                return ResourceManager.GetString("Message_ClearLyricCache_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Message_Information {
            get {
                return ResourceManager.GetString("Message_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last.FM credentials could not be authenticated. Please make sure you have entered the correct username and password, and that your account is not currently locked..
        /// </summary>
        public static string Message_LastFM_Authentication_Fail {
            get {
                return ResourceManager.GetString("Message_LastFM_Authentication_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last.FM credentials were successfully authenticated..
        /// </summary>
        public static string Message_LastFM_Authentication_Success {
            get {
                return ResourceManager.GetString("Message_LastFM_Authentication_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.FM Authentication.
        /// </summary>
        public static string Message_LastFM_Authentication_Title {
            get {
                return ResourceManager.GetString("Message_LastFM_Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ListenBrainz credentials could not be authenticated. Please make sure you have entered the correct user token..
        /// </summary>
        public static string Message_ListenBrainz_Authentication_Fail {
            get {
                return ResourceManager.GetString("Message_ListenBrainz_Authentication_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ListenBrainz credentials were successfully authenticated..
        /// </summary>
        public static string Message_ListenBrainz_Authentication_Success {
            get {
                return ResourceManager.GetString("Message_ListenBrainz_Authentication_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListenBrainz Authentication.
        /// </summary>
        public static string Message_ListenBrainz_Authentication_Title {
            get {
                return ResourceManager.GetString("Message_ListenBrainz_Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Message_No {
            get {
                return ResourceManager.GetString("Message_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Message_Yes {
            get {
                return ResourceManager.GetString("Message_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Discord Rich Presence.
        /// </summary>
        public static string Settings_Discord_EnableRP {
            get {
                return ResourceManager.GetString("Settings_Discord_EnableRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear lyrics cache.
        /// </summary>
        public static string Settings_Discord_Lyrics_ClearCache {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show song lyrics in Rich Presence.
        /// </summary>
        public static string Settings_Discord_Lyrics_EnableLyrics {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_EnableLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lyrics cache.
        /// </summary>
        public static string Settings_Discord_Lyrics_OpenCache {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_OpenCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced Lyrics (experimental).
        /// </summary>
        public static string Settings_Discord_Lyrics_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep lyrics during instrumental breaks.
        /// </summary>
        public static string Settings_Discord_Lyrics_ShowDuringBreak {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_ShowDuringBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During breaks in the music, keep showing the last played lyrics..
        /// </summary>
        public static string Settings_Discord_Lyrics_ShowDuringBreak_Description {
            get {
                return ResourceManager.GetString("Settings_Discord_Lyrics_ShowDuringBreak_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Rich Presence.
        /// </summary>
        public static string Settings_Discord_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Discord_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord RP.
        /// </summary>
        public static string Settings_Discord_SectionTitleShort {
            get {
                return ResourceManager.GetString("Settings_Discord_SectionTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show album artwork.
        /// </summary>
        public static string Settings_Discord_ShowAlbumArt {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowAlbumArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Apple Music icon.
        /// </summary>
        public static string Settings_Discord_ShowAppleMusicIcon {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowAppleMusicIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the Apple Music icon next to the album artwork in the Rich Presence display..
        /// </summary>
        public static string Settings_Discord_ShowAppleMusicIcon_Description {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowAppleMusicIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show when music is paused.
        /// </summary>
        public static string Settings_Discord_ShowWhenPaused {
            get {
                return ResourceManager.GetString("Settings_Discord_ShowWhenPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Discord status as.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Music.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay_AppleMusic {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay_AppleMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist name.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay_Artist {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song name.
        /// </summary>
        public static string Settings_Discord_UserStatusDisplay_SongName {
            get {
                return ResourceManager.GetString("Settings_Discord_UserStatusDisplay_SongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Music region.
        /// </summary>
        public static string Settings_General_AppleMusicRegion {
            get {
                return ResourceManager.GetString("Settings_General_AppleMusicRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country code of the region of your Apple Account (e.g. US)..
        /// </summary>
        public static string Settings_General_AppleMusicRegion_Description {
            get {
                return ResourceManager.GetString("Settings_General_AppleMusicRegion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat composer as artist.
        /// </summary>
        public static string Settings_General_ComposerAsArtist {
            get {
                return ResourceManager.GetString("Settings_General_ComposerAsArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For classical music tracks, use the composer as the artist instead of the performer..
        /// </summary>
        public static string Settings_General_ComposerAsArtist_Description {
            get {
                return ResourceManager.GetString("Settings_General_ComposerAsArtist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run when Windows starts.
        /// </summary>
        public static string Settings_General_RunOnWindowsStartup {
            get {
                return ResourceManager.GetString("Settings_General_RunOnWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_General_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is not a valid region code for Apple Music..
        /// </summary>
        public static string Settings_General_TooltipAppleMusicRegionError {
            get {
                return ResourceManager.GetString("Settings_General_TooltipAppleMusicRegionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string Settings_General_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Settings_General_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up album name.
        /// </summary>
        public static string Settings_Scrobbling_CleanAlbumName {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_CleanAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove common suffixes like &quot;Single&quot; and &quot;EP&quot; from album names..
        /// </summary>
        public static string Settings_Scrobbling_CleanAlbumName_Description {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_CleanAlbumName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_ApiKey {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API secret.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_ApiSecret {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_ApiSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Last.FM scrobbling.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_Enable {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_Password {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save credentials.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_SaveCredentials {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_SaveCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.FM.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_Scrobbling_LastFM_Username {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_LastFM_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ListenBrainz scrobbling.
        /// </summary>
        public static string Settings_Scrobbling_ListenBrainz_Enable {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ListenBrainz_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListenBrainz.
        /// </summary>
        public static string Settings_Scrobbling_ListenBrainz_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ListenBrainz_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User token.
        /// </summary>
        public static string Settings_Scrobbling_ListenBrainz_UserToken {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ListenBrainz_UserToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only scrobble the first artist.
        /// </summary>
        public static string Settings_Scrobbling_ScrobblePrimaryArtist {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ScrobblePrimaryArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum scrobble wait:.
        /// </summary>
        public static string Settings_Scrobbling_ScrobbleTime {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ScrobbleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After this amount of time has passed, scrobble the song if it hasn&apos;t been scrobbled already..
        /// </summary>
        public static string Settings_Scrobbling_ScrobbleTime_Description {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_ScrobbleTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrobbling.
        /// </summary>
        public static string Settings_Scrobbling_SectionTitle {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use song duration from Apple Music website.
        /// </summary>
        public static string Settings_Scrobbling_SongDurationChoice {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_SongDurationChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the length of the song from the Apple Music website instead of the Last.FM website. Slower but may yield better results..
        /// </summary>
        public static string Settings_Scrobbling_SongDurationChoice_Description {
            get {
                return ResourceManager.GetString("Settings_Scrobbling_SongDurationChoice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string Settings_TimeUnitSeconds {
            get {
                return ResourceManager.GetString("Settings_TimeUnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Taskbar_Exit_Title {
            get {
                return ResourceManager.GetString("Taskbar_Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Taskbar_Settings_Title {
            get {
                return ResourceManager.GetString("Taskbar_Settings_Title", resourceCulture);
            }
        }
    }
}
